markdown: kramdown
permalink: /:title.html
auto: true
relative_permalinks: false

safe: true
lsi: false
#pygments: true

name: Foobnix Player
description: Lightweight and Functional music player for Linux

author: Ivan Ivanenko
email: ivan.ivanenko@gmail.com
site: www.foobnix.com

url: http://foobnix.com

foobnix_version: 3.0.04
